title: "Christian Bongiorno"
email: "christian.bongiorno@centralesupelec.fr"
description: "Christian Bongiorno's professional profile and publications."
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://bongiornoc.github.io" # the base hostname & protocol for your site
github_username: "bongiornoc"

# Build settings
markdown: kramdown
theme: minima

# Author settings
author:
  name: "Christian Bongiorno"
  email: "christian.bongiorno@centralesupelec.fr"

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-toc

# Table of Contents settings
toc:
  min_level: 2
  max_level: 6
  no_toc_section_class: "no_toc"
  list_class: "toc-list"
  item_class: "toc-list-item"
  sublist_class: "toc-sublist"
  no_toc_class: "toc-no-list"
  no_toc_section_id: "no_toc_section"

# Social media settings
social:
  twitter: your_twitter_handle
  github: bongiornoc
  linkedin: your_linkedin_profile

# Exclude from processing
exclude:
  - README.md

# Include in processing
include:
  - _pages

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Christian Bongiorno"